### ISSUE TITLE
Add to SublimeLinter package channel

### ISSUE THREAD

**Issue by groteworld** [jimhester/SublimeLinter-contrib-lintr#1]
If this is working, you should add it to the SublimeLinter Package Channel. Few pieces to change before then:
- Repo's name should really be `SublimeLinter-contrib-lintr`. 
- Get your Travis CI badge in order.
- Class should be named `Lintr`
- Just double check some wording in this package as this is a plugin for `lintr` not `R` itself.

After that, make a PR to [SublimeLinter/package_control_channel](https://github.com/SublimeLinter/package_control_channel) and you'll get the benefit of Package Control to distribute this.

**Comment by jimhester** [comment]
Those changes make sense, thanks!  I will get to this soon.

**Comment by groteworld** [comment]
Add first release and it's ready

**Comment by jimhester** [comment]
Ok this should be good to go now.  Thanks for your help!
