### ISSUE TITLE
cannot add by sublime package control

### ISSUE THREAD

**Issue by maxheld83** [jimhester/SublimeLinter-contrib-lintr#2]
Is it just me, or is this package not actually on wbonds package control right now?

**Comment by jimhester** [comment]
It is not just you, it is not on there yet see also #1.

I was waiting to add it until the `lintr` package for more stable, but it is fairly stable now so it can probably be added now.  I will hopefully get to it in the next few days.

**Comment by maxheld83** [comment]
thanks a bunch; sorry for the duplicate @jimhester
