### ISSUE TITLE
Cannot locate a lintr executable after install

### ISSUE THREAD

**Issue by josiekre** [jimhester/SublimeLinter-contrib-lintr#4]
The README.md says:

> In order for R to be executed by SublimeLinter, you must ensure that its path is available to SublimeLinter. Before going any further, please read and follow the steps in “Finding a linter executable” through “Validating your PATH” in the documentation.

After install by running `install_github('jimhester/lintr')` inside R (that was installed with homebrew), `which lintr` doesn't find anything. 

If R is supposed to be the executable, `which R` returns `/usr/local/bin/r`, which is where my other functioning linters are located and running smoothly. 

What am I missing?

**Comment by josiekre** [comment]
I got it to work on another computer. So let me mess around with some things and get back to you with questions if I still can't figure it out.

**Comment by josiekre** [comment]
Got it. This package doesn't play well with Enhanced-R. Not sure why yet exactly but Enhanced-R needs to be disabled for the linting to work.

**Comment by josiekre** [comment]
No need to fix this. I see support with R-Box.

**Comment by jimhester** [comment]
This is related to #3.  It is good to hear that it works with R-Box though, after merging #3 it should also work with Enhanced-R as well.

**Comment by josiekre** [comment]
R-Box requires that some text be added to the user settings as outlined on R-Box's readme. Otherwise it won't work. This may be the same for Enhanced-R.
